#!/usr/bin/env python3
"""Export reviewer-facing rows into a bundled Expo TypeScript data module."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "mobile" / "src" / "data" / "static-review-pool.ts"
sys.path.insert(0, str(ROOT))

from contextsafe_hsd.api_server import ApiConfig, review_seed, resolve_path  # noqa: E402


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Freeze reviewer-facing data into the Expo app bundle."
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--limit", type=int, default=1154)
    parser.add_argument("--protected-csv", type=Path)
    parser.add_argument("--validation-json", type=Path)
    parser.add_argument("--restatement-col")
    parser.add_argument("--admin-runs-dir", type=Path)
    return parser


def review_item(row: dict[str, Any], index: int) -> dict[str, Any]:
    classifier_label = row.get("classifierLabel")
    risk_level = row.get("riskLevel")
    return {
        "id": str(row.get("id") or f"case-{index + 1}"),
        "source": str(row.get("source") or row.get("id") or f"case-{index + 1}"),
        "protectedText": str(row.get("protectedText") or ""),
        "restatement": str(row.get("restatement") or row.get("protectedText") or ""),
        "classifierLabel": "hate" if classifier_label == "hate" else "not_hate",
        "classifierScore": (
            row["classifierScore"] if isinstance(row.get("classifierScore"), (int, float)) else 0
        ),
        "riskLevel": risk_level if risk_level in {"low", "medium", "high"} else "medium",
        "guardFindings": row.get("guardFindings")
        if isinstance(row.get("guardFindings"), list)
        else [],
        "decision": "pending",
    }


def main() -> None:
    args = build_parser().parse_args()
    default_config = ApiConfig()
    config = ApiConfig(
        protected_csv=resolve_path(args.protected_csv) or default_config.protected_csv,
        validation_json=resolve_path(args.validation_json) or default_config.validation_json,
        restatement_col=args.restatement_col,
        admin_runs_dir=resolve_path(args.admin_runs_dir) or default_config.admin_runs_dir,
    )
    rows = review_seed(config, limit=args.limit)
    items = [review_item(row, index) for index, row in enumerate(rows)]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        "\n".join(
            [
                "/* Auto-generated by scripts/export_static_review_pool.py. */",
                "import { type ReviewItem } from './review-data';",
                "",
                f"export const staticReviewSeedItems: ReviewItem[] = {json.dumps(items, ensure_ascii=True, indent=2)};",
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(f"Wrote {len(items)} review items to {args.output}")


if __name__ == "__main__":
    main()
